INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj1", "Health", 100000, "9/1/18", "9/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj2", "Health", 100000, "9/1/18", "9/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj3", "Health", 100000, "9/1/18", "9/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj4", "Health", 100000, "9/1/18", "9/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj5", "Health", 100000, "9/1/18", "9/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj6", "Health", 100000, "9/1/18", "9/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj7", "Health", 100000, "9/1/18", "9/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj8", "Health", 100000, "9/1/18", "9/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj9", "Health", 100000, "9/1/18", "9/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj10", "Health", 100000, "9/1/18", "9/30/19");

INSERT INTO users (name, age) VALUES ("Henry", 27);
INSERT INTO users (name, age) VALUES ("Abigail", 19);
INSERT INTO users (name, age) VALUES ("John", 31);
INSERT INTO users (name, age) VALUES ("Matt", 25);
INSERT INTO users (name, age) VALUES ("Josh", 25);
INSERT INTO users (name, age) VALUES ("Phil", 60);
INSERT INTO users (name, age) VALUES ("Dana", 45);
INSERT INTO users (name, age) VALUES ("Melissa", 24);
INSERT INTO users (name, age) VALUES ("Spencer", 32);
INSERT INTO users (name, age) VALUES ("Greg", 29);
INSERT INTO users (name, age) VALUES ("David", 35);
INSERT INTO users (name, age) VALUES ("Helen", 18);
INSERT INTO users (name, age) VALUES ("Angie", 57);
INSERT INTO users (name, age) VALUES ("Bobby", 90);
INSERT INTO users (name, age) VALUES ("Mandy", 43);
INSERT INTO users (name, age) VALUES ("Toby", 34);
INSERT INTO users (name, age) VALUES ("Hannah", 23);
INSERT INTO users (name, age) VALUES ("Bryce", 27);
INSERT INTO users (name, age) VALUES ("Colt", 27);
INSERT INTO users (name, age) VALUES ("Zach", 28);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 16, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 7, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 13, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 18, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 11, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 13, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 18, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 13, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 15, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 19, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 2);


